import { describe, expect, it, beforeEach } from "vitest";
import { ControlledDemoAdapter } from "./demoAdapter";
import type { CharterDraft } from "../domain/types";

const draft: CharterDraft = { schema_version: "BINARY_EVENT_V1", domain: "SLA", question: "Did the service respond by the deadline?", allowed_outcomes: "YES,NO", event_deadline: 10, evidence_deadline: 20, temporal_semantics: "OCCURRENCE_BY_DEADLINE", authority_policy: "FROZEN_AUTHORITY_SNAPSHOT", source_policy: "HTTPS_BOUND_TO_AUTHORITY", min_corroboration: 1, conflict_policy: "CONFLICT_IS_INCONCLUSIVE", unavailable_source_policy: "SOURCE_UNAVAILABLE_IS_NON_BUSINESS_STATE", challenge_window_seconds: 30, max_challenge_generations: 2 };

describe("controlled protocol adapter", () => {
  beforeEach(() => localStorage.clear());
  it("labels itself controlled demo mode", async () => { const adapter = new ControlledDemoAdapter(); expect(adapter.mode).toBe("demo"); expect(adapter.label).toContain("CONTROLLED DEMO"); });
  it("does not fabricate a deployed address", async () => { const status = await new ControlledDemoAdapter().network(); expect(status.configured).toBe(false); expect(status.contractAddress).toContain("NO_ADDRESS"); });
  it("reads a canonical frozen charter fixture", async () => { const charter = await new ControlledDemoAdapter().getCharter("CHR-00000001"); expect(charter.state).toBe("FROZEN"); expect(charter.charter_hash).toMatch(/^0x[a-f0-9]{64}$/); });
  it("preserves authority identity separately from URL transport", async () => { const charter = await new ControlledDemoAdapter().getCharter("CHR-00000001"); expect(charter.authority_snapshot?.[0].authority_id).toBe("official-record"); expect(charter.authority_snapshot?.[0].hostname).not.toContain("https://"); });
  it("reads the semantic fact vector without prose", async () => { const resolution = await new ControlledDemoAdapter().getResolution("RES-00000001"); expect(Object.keys(resolution.semantic_result)).toHaveLength(8); expect(resolution.semantic_result.selected_outcome).toBe("YES"); });
  it("reads typed case lineage", async () => { const history = await new ControlledDemoAdapter().getResolutionHistory("CASE-00000001"); expect(history[0].status).toBe("ACTIVE"); expect(history[0].previous_resolution_id).toBe(""); });
  it("creates a draft charter through the same action interface", async () => { const adapter = new ControlledDemoAdapter(); const tx = await adapter.submit({ type: "create_charter", payload: draft }); expect(tx.hash.startsWith("demo:create_charter:")).toBe(true); const ids = await adapter.getCharterIds(); expect(ids.at(-1)).toBe("CHR-00000002"); expect((await adapter.getCharter("CHR-00000002")).state).toBe("DRAFT"); });
  it("rejects freezing a charter without an authority", async () => { const adapter = new ControlledDemoAdapter(); await adapter.submit({ type: "create_charter", payload: draft }); await expect(adapter.submit({ type: "freeze_charter", charterId: "CHR-00000002" })).rejects.toThrow("AUTHORITY_REQUIRED"); });
  it("enforces immutable freeze behavior", async () => { const adapter = new ControlledDemoAdapter(); await expect(adapter.submit({ type: "add_authority_rule", charterId: "CHR-00000001", payload: { authority_id: "new", authority_class: "PUBLIC", hostname: "new.example.org", path_prefix: "/", subject: "new", priority: 2 } })).rejects.toThrow("CHARTER_ALREADY_FROZEN"); });
  it("supports canonical evidence sealing", async () => { const adapter = new ControlledDemoAdapter(); const result = await adapter.submit({ type: "seal_evidence", caseId: "CASE-00000001" }); expect(result.hash).toContain("seal_evidence"); expect((await adapter.getCase("CASE-00000001")).evidence_root).toBeTruthy(); });
  it("supports new-evidence challenge and preserves generations", async () => { const adapter = new ControlledDemoAdapter(); await adapter.submit({ type: "challenge", caseId: "CASE-00000001", ground: "NEW_ADMISSIBLE_EVIDENCE", evidenceId: "EVID-00000002" }); expect((await adapter.getCase("CASE-00000001")).state).toBe("CHALLENGED"); await adapter.submit({ type: "readjudicate", caseId: "CASE-00000001" }); const history = await adapter.getResolutionHistory("CASE-00000001"); expect(history).toHaveLength(2); expect(history[0].status).toBe("SUPERSEDED"); });
  it("makes terminal finality readable", async () => { const adapter = new ControlledDemoAdapter(); await adapter.submit({ type: "challenge", caseId: "CASE-00000001", ground: "NEW_ADMISSIBLE_EVIDENCE", evidenceId: "EVID-00000002" }); await adapter.submit({ type: "readjudicate", caseId: "CASE-00000001" }); await adapter.submit({ type: "finalize_case", caseId: "CASE-00000001" }); expect((await adapter.getCase("CASE-00000001")).terminal).toBe(true); expect((await adapter.getResolution("RES-00000002")).status).toBe("FINAL"); });
});
