from __future__ import annotations

import os
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))


# genlayer-test 0.30.0rc2 keeps fd 0 mapped to its injected temporary
# calldata file. On Windows, the loader's immediate os.unlink therefore gets
# WinError 32 even though the file is intentionally short-lived. Keep this
# narrow test-only compatibility shim scoped to autogenerated temp files; it
# does not affect contract code or ordinary repository cleanup.
if os.name == "nt":
    _unlink = os.unlink
    _temp_root = os.path.normcase(os.path.abspath(tempfile.gettempdir()))

    def _unlink_genlayer_temp(path, *args, **kwargs):
        try:
            _unlink(path, *args, **kwargs)
        except PermissionError:
            candidate = os.path.normcase(os.path.abspath(os.fspath(path)))
            if not candidate.startswith(_temp_root) or not os.path.basename(candidate).startswith("tmp"):
                raise

    os.unlink = _unlink_genlayer_temp


# genlayer-test 0.30.0rc2 can target either the older v0.6 compatibility layout
# or the current v0.6 layout. Keep this compatibility patch test-only and fall
# back to the installed public modules when `genlayer.py.*` is absent.
try:
    import importlib
    from gltest.direct import loader as _direct_loader
    from gltest.direct import sdk_compat as _sdk_compat

    def _import_calldata_rc():
        try:
            return importlib.import_module("genlayer.py.calldata")
        except ModuleNotFoundError:
            return importlib.import_module("genlayer.calldata")

    def _import_types_rc():
        try:
            return importlib.import_module("genlayer.py.types")
        except ModuleNotFoundError:
            return importlib.import_module("genlayer.types")

    _sdk_compat.import_calldata = _import_calldata_rc
    _sdk_compat.import_types = _import_types_rc
    _direct_loader.import_calldata = _import_calldata_rc
    from gltest.direct import wasi_mock as _wasi_mock_compat
    _wasi_mock_compat.import_calldata = _import_calldata_rc
except ImportError:
    pass


# Direct mode in this RC does not yet patch the v0.6 module path
# `genlayer.gl.vm`. Execute the leader locally and retain the validator closure
# so the suite can independently run the validator afterward.
try:
    import importlib
    import sys as _sys
    from gltest.direct import wasi_mock as _wasi_mock

    _gl_vm = importlib.import_module("genlayer.gl.vm")
    _sys.modules["genlayer.vm"] = _gl_vm

    def _run_nondet_direct(leader_fn, validator_fn, /, **kwargs):
        result = leader_fn()
        _wasi_mock.get_vm()._captured_validators.append((result, leader_fn, validator_fn))
        return result

    _gl_vm.run_nondet_unsafe = _run_nondet_direct
    _gl_vm.run_nondet = _run_nondet_direct
except ImportError:
    pass


# The v0.6 RC SDK exposes `gl.message` as an immutable NamedTuple snapshot,
# while genlayer-test's v0.3 compatibility shim only refreshes the old
# `genlayer.message` module. Keep the test VM's sender/value cheatcodes aligned
# with the current RC surface.
try:
    from gltest.direct.vm import VMContext as _VMContext
    _original_refresh_gl_message = _VMContext._refresh_gl_message

    def _refresh_gl_message_rc(self):
        import importlib
        import sys as _sys

        if "genlayer.gl" not in _sys.modules:
            return _original_refresh_gl_message(self)
        gl_module = importlib.import_module("genlayer.gl")
        try:
            types_module = importlib.import_module("genlayer.py.types")
        except ModuleNotFoundError:
            types_module = importlib.import_module("genlayer.types")
        Address = types_module.Address
        u256 = types_module.u256

        def as_address(value):
            if isinstance(value, Address):
                return value
            if isinstance(value, bytes):
                return Address(value)
            if hasattr(value, "as_bytes"):
                return Address(value.as_bytes)
            return value

        sender = as_address(self.sender)
        origin = as_address(self.origin)
        contract_address = as_address(self._contract_address)
        raw = dict(gl_module.message_raw)
        raw["sender_address"] = sender
        raw["origin_address"] = origin
        raw["contract_address"] = contract_address
        raw["value"] = self._value
        raw["chain_id"] = self._chain_id
        raw["datetime"] = self._datetime
        gl_module.message_raw = raw
        gl_module.message = gl_module.MessageType(
            contract_address=contract_address,
            sender_address=sender,
            origin_address=origin,
            value=u256(self._value),
            chain_id=u256(self._chain_id),
        )

    _VMContext._refresh_gl_message = _refresh_gl_message_rc
except ImportError:
    pass


# The same RC mismatch leaves `__type_desc__` unset on the contract record
# returned by the bundled direct allocator, although its generated field
# properties require it. Patch only the test allocator so direct-mode tests
# exercise the real contract fields without changing the production contract.
try:
    from gltest.direct import loader as _direct_loader

    def _allocate_contract_rc(contract_cls, vm, *args, **kwargs):
        try:
            from genlayer.py.storage import ROOT_SLOT_ID
            from genlayer.py.storage._internal.generate import ORIGINAL_INIT_ATTR, _storage_build
            builder_args = ({},)
        except ModuleNotFoundError:
            from genlayer.storage import ROOT_SLOT_ID
            from genlayer.storage._internal.generate import (
                ORIGINAL_INIT_ATTR,
                _BuilderCtx,
                _storage_build,
            )
            builder_args = (_BuilderCtx.empty(),)

        type_desc = _storage_build(*builder_args, contract_cls)
        slot = vm._storage.get_store_slot(ROOT_SLOT_ID)
        instance = type_desc.get(slot, 0)
        if not hasattr(instance, "__type_desc__"):
            instance.__type_desc__ = type_desc
        init_owner = getattr(type_desc, "cls", None)
        init = getattr(init_owner, "__init__", None) if init_owner is not None else getattr(contract_cls, "__init__", None)
        if init is not None and hasattr(init, ORIGINAL_INIT_ATTR):
            init = getattr(init, ORIGINAL_INIT_ATTR)
        if init is not None:
            init(instance, *args, **kwargs)
        return instance

    _direct_loader._allocate_contract = _allocate_contract_rc
except ImportError:
    pass
