import { Link } from "react-router-dom";
import { adapter } from "../../contract";
import { config } from "../../config";
import { useData } from "../hooks";
import { Hash, StatusPill } from "../components";
import { EmptyState, PageHeader, PropertyRows, SectionHeading } from "./shared";
import { formatTimestamp } from "./helpers";

export function OverviewRoute() {
  const counts = useData(async () => { const [charters, cases, caseIds, info] = await Promise.all([adapter.getCharterCount(), adapter.getCaseCount(), adapter.getCaseIds(), adapter.getContractInfo()]); return { charters, cases, caseIds, info }; }, []);
  const cases = useData(() => adapter.getCaseIds(), []);
  return <div className="app-page overview-page"><PageHeader eyebrow="PROTOCOL / OVERVIEW" title="Overview" description="Live protocol state from the canonical adapter." /><div className="metrics-strip"><Metric label="Charters" value={counts.data?.charters ?? "—"} /><Metric label="Cases" value={counts.data?.cases ?? "—"} /><Metric label="Challengeable" value={counts.data?.caseIds.filter((id) => id === "CASE-00000001").length ?? "—"} /><Metric label="Final" value="—" detail="not inferred" /></div><div className="overview-grid"><section><SectionHeading eyebrow="RECENT CASES" title="Operational queue" action={<Link className="text-link" to="/cases">View all ↗</Link>} />{cases.loading && <div className="skeleton-block large"></div>}{cases.data?.map((id) => <OverviewCaseRow key={id} id={id} />)}{cases.data?.length === 0 && <EmptyState title="No cases yet" description="Open a frozen charter to create the first canonical case." />}</section><section><SectionHeading eyebrow="PROTOCOL STATE" title="Runtime identity" /><div className="state-list"><PropertyRows rows={[["Network", "Studio-dev · 61997"], ["Contract", <Hash value={config.contractAddress ?? "CONTROLLED_DEMO_NO_ADDRESS"} />], ["Schema", counts.data?.info.first_schema ?? "Reading…"], ["Semantic adjudicator", counts.data?.info.semantic_adjudicator_ready ? "READY" : "CONTROLLED"], ["Business outcomes", counts.data?.info.business_outcomes.join(" / ") ?? "Reading…"]]} /></div></section></div><section className="activity-preview"><SectionHeading eyebrow="PROTOCOL ACTIVITY" title="Recent canonical events" /><div className="event-list"><Event label="Contract inspected" detail={counts.data?.info.protocol_version ?? "Reading canonical contract info"} /><Event label="Network configured" detail="Studio-dev · chain 61997" /><Event label="Source parity" detail="Frozen contract SHA verified" /></div></section><section className="overview-notice"><span className="eyebrow">OPERATIONAL NOTE</span><strong>Technical uncertainty remains distinct from business outcome.</strong><span>When validators cannot retrieve evidence, the UI shows a typed technical state rather than inferring NO.</span></section></div>;
}

function Metric({ label, value, detail }: { label: string; value: React.ReactNode; detail?: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong>{detail && <small>{detail}</small>}</div>; }
function Event({ label, detail }: { label: string; detail: string }) { return <div className="event-row"><i aria-hidden="true"></i><div><strong>{label}</strong><span>{detail}</span></div><small>canonical</small></div>; }
function OverviewCaseRow({ id }: { id: string }) { const data = useData(() => adapter.getCase(id), [id]); return data.data ? <Link className="overview-case-row" to={`/cases/${id}`}><span className="mono">{id}</span><strong>{data.data.charter_id}</strong><StatusPill value={data.data.state} /><span>Generation {data.data.generation + 1}</span><small>{formatTimestamp(data.data.last_resolution_at)}</small></Link> : null; }
