import { Link } from "react-router-dom";
import { useState, type ReactNode } from "react";
import { adapter } from "../../contract";
import { config, contractDisplayAddress } from "../../config";
import { SCHEMA_VERSION } from "../../domain/types";
import { PUBLIC_METHODS } from "../../contract/abi";
import { useData } from "../hooks";
import { Hash, StatusPill } from "../components";
import { PageHeader, PropertyRows, SectionHeading } from "./shared";

export function LandingRoute() {
  return <div className="public-page landing-page"><section className="landing-hero public-width"><div className="landing-hero-copy"><div className="eyebrow">SEMANTIC SETTLEMENT INFRASTRUCTURE</div><h1>Freeze the <em>rules</em><br />before the outcome matters.</h1><p>CharterLock freezes interpretation rules, binds authority-qualified evidence, lets validators determine bounded facts, and derives the outcome deterministically.</p><div className="hero-actions"><Link className="button primary" to="/app">Launch CharterLock</Link><Link className="button secondary" to="/proof">Verify deployment</Link></div><div className="trust-strip"><span>Studio-dev · Chain 61997</span><span>Source verified</span><span>21 public methods</span><span>v1.0.0 live</span></div><span className="controlled-note">CONTROLLED DEMO / TEST MODE · live reads are separated from local fixtures</span></div><ProtocolSpecimen /></section><ProblemSection /><ProtocolFlow /><FirewallSection /><EvidencePipeline /><SemanticFirewall /><ChallengeLineage /><LiveProof /><section className="public-cta public-width"><div><span className="eyebrow">READY TO INSPECT THE PROTOCOL?</span><h2>Open the canonical console.</h2></div><Link className="button primary" to="/app">Open protocol <span>↗</span></Link></section></div>;
}

function ProtocolSpecimen() {
  return <div className="protocol-specimen"><div className="specimen-top"><span className="specimen-mark">C</span><span>CHARTERLOCK / PROTOCOL SPECIMEN</span><span className="specimen-state"><i></i>FROZEN</span></div><div className="specimen-question"><span className="eyebrow">RESOLUTION CHARTER</span><strong>Did the designated authority confirm the event before the deadline?</strong></div><div className="specimen-columns"><div><span>AUTHORITY</span><strong>IANA</strong><code>www.iana.org</code></div><div><span>EVIDENCE</span><strong>SHA verified</strong><code>6,661 bytes</code></div></div><div className="specimen-facts"><span className="eyebrow">SEMANTIC FACTS</span><div><span>Event occurred</span><b>—</b></div><div><span>Authority met</span><b>—</b></div><div><span>Evidence sufficient</span><b>—</b></div></div><div className="specimen-result"><span>CANONICAL RESULT</span><strong>SOURCE_UNAVAILABLE</strong><small>Business outcome · Not produced</small></div></div>;
}

function ProblemSection() {
  return <section className="public-section public-width problem-section"><div className="section-lead"><span className="eyebrow">THE PROBLEM</span><h2>Most resolution systems let someone rewrite the rules after exposure.</h2></div><div className="editorial-copy"><p>Administrator discretion, oracle ambiguity, post-event clarification, model discretion, and evidence substitution all create the same failure: the constitution of a decision changes after the world is known.</p><p>CharterLock closes that gap by making the question, authority, timing, evidence identity, and challenge constitution explicit before a case can resolve.</p></div></section>;
}

function ProtocolFlow() {
  const steps = [["01", "FREEZE CHARTER", "Question, policy, deadlines"], ["02", "BIND AUTHORITY", "Hostname and path constitution"], ["03", "SEAL EVIDENCE", "Exact bytes and digest"], ["04", "VALIDATOR FACTS", "Independent retrieval"], ["05", "DETERMINISTIC OUTCOME", "Canonical state"]];
  return <section className="public-section public-width"><SectionHeading eyebrow="THE PROTOCOL" title="Interpretation becomes a controlled pipeline." /><div className="protocol-flow-large">{steps.map(([number, title, detail], index) => <div className="protocol-flow-stage" key={number}><span>{number}</span><strong>{title}</strong><small>{detail}</small>{index < steps.length - 1 && <i aria-hidden="true" />}</div>)}</div></section>;
}

function FirewallSection() {
  return <section className="public-section public-width firewall-section"><SectionHeading eyebrow="INTERPRETATION FIREWALL" title="The rules stop moving when the charter freezes." /><div className="firewall-split"><div><span className="firewall-label">BEFORE FREEZE</span><ul><li>Question</li><li>Temporal semantics</li><li>Authority policy</li><li>Evidence requirements</li><li>Challenge rules</li></ul></div><div className="firewall-divider"><span>LOCK</span></div><div className="locked-side"><span className="firewall-label">AFTER FREEZE</span><ul><li>No administrator override</li><li>No setOutcome</li><li>No replacement of history</li><li>No mutable interpretation</li><li>No reopening final cases</li></ul></div></div></section>;
}

function EvidencePipeline() {
  const steps = ["URL", "Authority binding", "Exact bytes", "SHA-256", "Admissibility", "Semantic interpretation"];
  return <section className="public-section public-width evidence-pipeline-section"><div className="section-lead"><span className="eyebrow">EVIDENCE BEFORE SEMANTICS</span><h2>Transport is not identity.</h2></div><div className="evidence-pipeline">{steps.map((step, index) => <div key={step} className="pipeline-step"><span>{String(index + 1).padStart(2, "0")}</span><strong>{step}</strong>{index < steps.length - 1 && <i aria-hidden="true">↓</i>}</div>)}</div><div className="transport-note"><span>TRANSPORT</span><b>≠</b><span>IDENTITY</span><small>HTTP success alone never makes evidence admissible.</small></div></section>;
}

function SemanticFirewall() {
  const facts = ["event_occurred", "event_before_deadline", "confirmation_before_deadline", "authority_requirement_met", "corroboration_requirement_met", "evidence_conflict", "evidence_sufficient", "selected_outcome"];
  return <section className="public-section public-width semantic-firewall"><div className="section-lead"><span className="eyebrow">SEMANTIC FIREWALL</span><h2>Validators determine facts. Code derives state.</h2><p>The bounded vector is the only semantic payload that crosses into deterministic business logic.</p></div><div className="semantic-firewall-table"><div className="semantic-firewall-head"><span>FIELD</span><span>BOUNDED VALUE</span><span>OWNER</span></div>{facts.map((fact) => <div key={fact}><code>{fact}</code><span>{fact === "selected_outcome" ? "YES · NO · INCONCLUSIVE" : "TRUE · FALSE"}</span><small>{fact === "selected_outcome" ? "deterministic contract" : "validator fact"}</small></div>)}</div></section>;
}

function ChallengeLineage() {
  return <section className="public-section public-width challenge-lineage"><SectionHeading eyebrow="CHALLENGE LINEAGE" title="History is appended, never rewritten." /><div className="public-lineage"><div><span>GENERATION 0</span><strong>RES-00000001</strong><small>Evidence root · canonical state</small></div><i>↓</i><div className="lineage-challenge"><span>NEW_ADMISSIBLE_EVIDENCE</span><strong>Challenge</strong></div><i>↓</i><div><span>GENERATION 1</span><strong>RES-00000002</strong><small>New evidence root · supersedes</small></div><i>↓</i><div className="lineage-final"><span>TERMINAL STATE</span><strong>FINAL</strong></div></div></section>;
}

function LiveProof() {
  return <section className="public-section public-width live-proof-section"><SectionHeading eyebrow="LIVE PROOF" title="A release you can inspect." action={<Link className="text-link" to="/proof">Open proof ↗</Link>} /><div className="live-proof-grid"><PropertyRows rows={[["Contract", <Hash value={contractDisplayAddress(config.mode, config.contractAddress)} />], ["Network", "Studio-dev · 61997"], ["Source SHA", <Hash value={config.sourceSha256} />]]} /><PropertyRows rows={[["Tests", "106 / 106"], ["Mutation", "20 / 20 killed"], ["CI", "6 / 6 jobs"], ["Production", <StatusPill value="LIVE" />]]} /></div></section>;
}

export function ProofRoute() {
  const info = useData(() => adapter.getContractInfo(), []);
  const network = useData(() => adapter.network(), []);
  const live = config.mode === "live";
  return <div className="public-page proof-page public-width"><PageHeader eyebrow="CHARTERLOCK / PROOF" title="Verify CharterLock." description="Everything required to independently identify the live release, its source, and its known limits." /><div className="proof-status-bar"><div><StatusPill value={live ? "LIVE" : "NOT DEPLOYED"} /><strong>CharterLock v1.0.0</strong></div><span>{live ? "SOURCE VERIFIED" : "CONTROLLED DEMO / TEST MODE"}</span></div><div className="proof-sections"><ProofSection title="Deployment" eyebrow="01"><PropertyRows rows={[["Network", "Studio-dev"], ["Chain", "61997"], ["Contract", <Hash value={config.contractAddress ?? "NOT DEPLOYED"} />], ["Deployment tx", <Hash value={config.deploymentTxHash} />]]} /></ProofSection><ProofSection title="Source" eyebrow="02"><PropertyRows rows={[["Source SHA", <Hash value={config.sourceSha256} />], ["Deployment source commit", "6d2a823e…"], ["Parity", "Verified against frozen release artifact"], ["Schema", info.data?.first_schema ?? SCHEMA_VERSION]]} /></ProofSection><ProofSection title="Release" eyebrow="03"><PropertyRows rows={[["Repository", <a href={config.repositoryUrl} target="_blank" rel="noreferrer">GIFTEDLOV/charterlock ↗</a>], ["Release", "v1.0.0"], ["Release HEAD", "4e093061…"], ["Branch protection", "Protected main"]]} /></ProofSection><ProofSection title="Validation" eyebrow="04"><PropertyRows rows={[["Python", "106 / 106"], ["Mutation", "20 / 20 killed"], ["Frontend", "57 / 57"], ["Browser", "12 / 12"]]} /></ProofSection><ProofSection title="Live qualification" eyebrow="05"><PropertyRows rows={[["Case", config.qualificationCaseId], ["Evidence root", "Canonical readback"], ["Consensus", live ? "PASS · execution verified" : "CONTROLLED"], ["Technical result", "SOURCE_UNAVAILABLE"], ["Business result", "NOT PRODUCED"]]} /></ProofSection><ProofSection title="Limitations" eyebrow="06" className="proof-limitations"><PropertyRows rows={[["Validator web retrieval", "PARTIAL · Studio-dev limitation"], ["Browser wallet", "PENDING MANUAL"], ["Finalization", "CHALLENGE WINDOW OPEN"]]} /></ProofSection></div><div className="proof-runtime"><span className="eyebrow">RUNTIME IDENTITY</span><PropertyRows rows={[["Configured chain", network.data ? `${network.data.chainId} · expected ${network.data.expectedChainId}` : "Reading…"], ["Contract match", network.data?.match ? "MATCHED" : live ? "NOT CONFIRMED" : "CONTROLLED"], ["Protocol", info.data?.protocol ?? "Reading…"]]} /></div><p className="proof-note">{live ? "LIVE reads reflect the deployed contract. Business YES/NO is not claimed where validators could not retrieve evidence." : "CONTROLLED DEMO / TEST MODE. Live proof becomes available only through the live adapter."}</p></div>;
}

function ProofSection({ eyebrow, title, className = "", children }: { eyebrow: string; title: string; className?: string; children: ReactNode }) { return <section className={`proof-section ${className}`}><div className="proof-section-title"><span>{eyebrow}</span><h2>{title}</h2></div>{children}</section>; }

export function IntegrateRoute() {
  const [selected, setSelected] = useState<string>(PUBLIC_METHODS[0]);
  const isView = selected.startsWith("get_") || selected === "contract_info";
  return <div className="public-page integrate-page public-width"><PageHeader eyebrow="CHARTERLOCK / DEVELOPERS" title="Build on the protocol." description="A stable method surface for applications that need rules, evidence, and outcomes to remain inspectable." /><div className="integration-intro"><div><span className="eyebrow">THE LIFECYCLE</span><div className="integration-flow"><span>PRECONDITION</span><i>→</i><span>PREPARE</span><i>→</i><span>BROADCAST ONCE</span><i>→</i><span>RECONCILE</span><i>→</i><span>READBACK</span></div></div><div className="integration-config"><span className="eyebrow">STUDIO-DEV CONFIGURATION</span><PropertyRows rows={[["SDK", "genlayer-js 2.0.0-rc.1"], ["Chain", "61997"], ["RPC", config.rpcUrl], ["Contract", <Hash value={contractDisplayAddress(config.mode, config.contractAddress)} />]]} /></div></div><div className="method-workspace"><aside className="method-nav"><div className="eyebrow">21 PUBLIC METHODS</div>{PUBLIC_METHODS.map((name) => <button key={name} type="button" className={selected === name ? "selected" : ""} onClick={() => setSelected(name)}><code>{name}</code><small>{name.startsWith("get_") || name === "contract_info" ? "VIEW" : "WRITE"}</small></button>)}</aside><article className="method-detail"><span className="eyebrow">{isView ? "READ METHOD" : "WRITE METHOD"}</span><h2><code>{selected}</code></h2><p>Call <code>{selected}</code> against the frozen {SCHEMA_VERSION} contract surface. In live mode, success is only confirmed after canonical readback.</p><PropertyRows rows={[["Network", "Studio-dev · 61997"], ["Canonical truth", "Contract readback"], ["Retry policy", "No blind rebroadcast"], ["Status", "Stable v1 surface"]]} /><pre className="code-block"><code>{["const result = await charterlock." + selected + "({", "  // schema-defined arguments", "});"].join("\n")}</code></pre></article></div></div>;
}
