import { beforeEach, describe, expect, it } from "vitest";
import type { ProtocolAction, ProtocolAdapter, ReconciliationResult, SubmittedTransaction } from "../domain/types";
import { executeTransaction, reconcilePersisted } from "./engine";
import { persistPendingTransaction, loadPendingTransactions } from "./persistence";

const action: ProtocolAction = { type: "finalize_case", caseId: "CASE-00000001" };
const submitted: SubmittedTransaction = { hash: "0xsame", action, createdAt: 1 };
const success: ReconciliationResult = { hash: submitted.hash, finalized: true, executionSucceeded: true, status: "FINALIZED" };

function fake(overrides: Partial<ProtocolAdapter> = {}): ProtocolAdapter {
  const base: ProtocolAdapter = {
    mode: "demo", label: "TEST", listCharterIds: async () => [], getCharterCount: async () => 0, getCharter: async () => { throw new Error("unused"); }, getCharterIds: async () => [], getCaseCount: async () => 0, getCaseIds: async () => [], getCase: async () => { throw new Error("unused"); }, getEvidenceIds: async () => [], getEvidence: async () => { throw new Error("unused"); }, getResolution: async () => { throw new Error("unused"); }, getResolutionHistory: async () => [], getContractInfo: async () => ({ protocol: "", protocol_version: "", first_schema: "", phase: "", semantic_adjudicator_ready: true, business_outcomes: [], technical_states: [], procedural_challenge_reason_codes: [], no_privileged_override: true, no_custody_or_betting: true, charter_count: 0, case_count: 0, evidence_count: 0 }), submit: async () => submitted, reconcile: async () => success, precondition: async () => ({}), verifyPostcondition: async () => true, network: async () => ({ chainId: 61997, expectedChainId: 61997, configured: false, match: false }),
  };
  return { ...base, ...overrides };
}

describe("transaction state machine", () => {
  beforeEach(() => localStorage.clear());
  it("blocks live writes on network mismatch before submit", async () => { let submittedCount = 0; const adapter = fake({ mode: "live", submit: async () => { submittedCount += 1; return submitted; } }); await expect(executeTransaction(adapter, action, "terminal", action.caseId)).rejects.toThrow("NETWORK_MISMATCH"); expect(submittedCount).toBe(0); });
  it("distinguishes finalized execution failure", async () => { const adapter = fake({ reconcile: async () => ({ ...success, executionSucceeded: false, status: "FINISHED_WITH_ERROR" }) }); await expect(executeTransaction(adapter, action, "terminal", action.caseId)).rejects.toThrow("FINALIZED_EXECUTION_FAILED"); expect(loadPendingTransactions()[0].phase).toBe("FINALIZED_EXECUTION_FAILED"); });
  it("distinguishes canonical postcondition mismatch", async () => { const adapter = fake({ verifyPostcondition: async () => false }); await expect(executeTransaction(adapter, action, "terminal", action.caseId)).rejects.toThrow("CANONICAL_POSTCONDITION_FAILED"); expect(loadPendingTransactions()[0].phase).toBe("CANONICAL_POSTCONDITION_FAILED"); });
  it("reconciles a persisted hash without calling submit and performs canonical readback", async () => { let verifyCalled = false; persistPendingTransaction({ hash: submitted.hash, action: submitted.action, actionType: action.type, entityId: action.caseId, expectedPostcondition: "terminal", precondition: { state: "READJUDICATED" }, createdAt: 1, chainId: 61997, phase: "HASH_PERSISTED" }); let submitCalled = false; const adapter = fake({ submit: async () => { submitCalled = true; return submitted; }, verifyPostcondition: async (value, precondition) => { verifyCalled = value.type === action.type && (precondition as { state: string }).state === "READJUDICATED"; return verifyCalled; } }); await reconcilePersisted(adapter); expect(submitCalled).toBe(false); expect(verifyCalled).toBe(true); expect(loadPendingTransactions()).toEqual([]); });
  it("keeps a same-hash record when startup canonical readback fails", async () => { persistPendingTransaction({ hash: submitted.hash, action: submitted.action, actionType: action.type, entityId: action.caseId, expectedPostcondition: "terminal", precondition: {}, createdAt: 1, chainId: 61997, phase: "HASH_PERSISTED" }); const adapter = fake({ verifyPostcondition: async () => false }); await reconcilePersisted(adapter); expect(loadPendingTransactions()[0].phase).toBe("CANONICAL_POSTCONDITION_FAILED"); });
  it("holds a persisted hash on startup when the live network mismatches", async () => { persistPendingTransaction({ hash: submitted.hash, action: submitted.action, actionType: action.type, entityId: action.caseId, expectedPostcondition: "terminal", precondition: {}, createdAt: 1, chainId: 61997, phase: "HASH_PERSISTED" }); const adapter = fake({ mode: "live", network: async () => ({ chainId: 61999, expectedChainId: 61997, configured: true, match: false }) }); await reconcilePersisted(adapter); expect(loadPendingTransactions()[0].phase).toBe("NETWORK_MISMATCH"); });
  it("maps wallet rejection to a typed failure", async () => { const adapter = fake({ submit: async () => { throw new Error("WALLET_REJECTED"); } }); await expect(executeTransaction(adapter, action, "terminal", action.caseId)).rejects.toThrow("WALLET_REJECTED"); });
});
